# -*- coding: utf-8 -*-

PROPERTY_ID = "ID"
PROPERTY_PARENT_ID = "Parent-ID"
PROPERTY_DEPARTMENT_NAME = "DepartmentName"
PROPERTY_DEPARTMENT_CITY = "DepartmentCity"
PROPERTY_FIRSTNAME = "Firstname"
PROPERTY_SURNAME = "Surname"
PROPERTY_DEPARTMENT_ID = "Department-ID"
PROPERTY_BIRTHDATE = "BirthDate"
